Remove EmbargoedZarrArchive since not supported
Apparently adding Zarrs to embargoed dandisets is not supported, so I
guess because of that adding EmbargoedZarrArchive here causes following error

[16:18:18] ERROR    Internal Server Error: /api/stats/                                          log.py:241
                    Traceback (most recent call last):
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/django/core/handlers/exception.py", line 55, in inner
                        response = get_response(request)
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/django/core/handlers/base.py", line 197, in _get_response
                        response = wrapped_callback(request, *callback_args, **callback_kwargs)
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/django/views/decorators/csrf.py", line 54, in wrapped_view
                        return view_func(*args, **kwargs)
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/django/views/generic/base.py", line 84, in view
                        return self.dispatch(request, *args, **kwargs)
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/rest_framework/views.py", line 509, in dispatch
                        response = self.handle_exception(exc)
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/rest_framework/views.py", line 469, in handle_exception
                        self.raise_uncaught_exception(exc)
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/rest_framework/views.py", line 480, in raise_uncaught_exception
                        raise exc
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/rest_framework/views.py", line 506, in dispatch
                        response = handler(request, *args, **kwargs)
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/rest_framework/decorators.py", line 50, in handler
                        return func(*args, **kwargs)
                      File "/home/yoh/proj/dandi/dandi-archive/dandiapi/api/views/stats.py",
                    line 13, in stats_view
                        size = Asset.total_size()
                      File "/home/yoh/proj/dandi/dandi-archive/dandiapi/api/models/asset.py",
                    line 302, in total_size
                        return sum(
                      File "/home/yoh/proj/dandi/dandi-archive/dandiapi/api/models/asset.py",
                    line 303, in <genexpr>
                        cls.objects.filter(assets__versions__isnull=False)
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/django/db/models/manager.py", line 85, in manager_method
                        return getattr(self.get_queryset(), name)(*args, **kwargs)
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/django/db/models/query.py", line 1071, in filter
                        return self._filter_or_exclude(False, args, kwargs)
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/django/db/models/query.py", line 1089, in _filter_or_exclude
                        clone._filter_or_exclude_inplace(negate, args, kwargs)
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
                        self._query.add_q(Q(*args, **kwargs))
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/django/db/models/sql/query.py", line 1502, in add_q
                        clause, _ = self._add_q(q_object, self.used_aliases)
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/django/db/models/sql/query.py", line 1532, in _add_q
                        child_clause, needed_inner = self.build_filter(
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/django/db/models/sql/query.py", line 1377, in build_filter
                        lookups, parts, reffed_expression = self.solve_lookup_type(arg)
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/django/db/models/sql/query.py", line 1187, in solve_lookup_type
                        _, field, _, lookup_parts = self.names_to_path(lookup_splitted,
                    self.get_meta())
                      File "/home/yoh/proj/dandi/dandi-archive/venvs/dev3/lib/python3.9/site-pa
                    ckages/django/db/models/sql/query.py", line 1677, in names_to_path
                        raise FieldError(
                    django.core.exceptions.FieldError: Cannot resolve keyword 'assets' into
                    field. Choices are: active_uploads, created, dandiset, dandiset_id,
                    file_count, id, modified, name, size, status, zarr_id